# Generated by Django 2.2.9 on 2020-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures_ru', '0002_auto_20200127_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlog_ru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=32, verbose_name='Имя: ')),
                ('blog_text', models.TextField(verbose_name='Текст: ')),
                ('blog_img', models.ImageField(default='default.jpg', upload_to='furnitures/about/', verbose_name='Фото: ')),
            ],
        ),
        migrations.CreateModel(
            name='AboutDiplom_ru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_txt', models.CharField(max_length=32, verbose_name='Имя Сертификата:')),
                ('diplom_img', models.ImageField(default='default.jpg', upload_to='furnitures/about/', verbose_name='Фото Сертификата')),
            ],
        ),
        migrations.CreateModel(
            name='AboutImage_ru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_main_image', models.ImageField(default='default.jpg', upload_to='furnitures/about/', verbose_name='Фото о нас: ')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo_ru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32, verbose_name='Имя Фирмы: ')),
                ('company_logo', models.ImageField(default='default.jpg', upload_to='furnitures/logo/', verbose_name='Логотип Фирмы: ')),
                ('company_slogan', models.CharField(max_length=128, verbose_name='Слоган Фирмы: ')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAddress_ru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map_link', models.TextField(verbose_name='Ссылка Google Карта')),
                ('store_img', models.ImageField(default='default.jpg', upload_to='furnitures/stores/', verbose_name='Фото Магазина')),
                ('address_line1', models.CharField(max_length=64, verbose_name='Аддресс Строка 1 : ')),
                ('address_line2', models.CharField(blank=True, max_length=64, verbose_name='Аддресс Строка 2 : ')),
                ('phone1', models.CharField(max_length=32, verbose_name='Телефон 1 ')),
                ('phone2', models.CharField(blank=True, max_length=32, verbose_name='Телефон 2 ')),
                ('phone3', models.CharField(blank=True, max_length=32, verbose_name='Телефон 3 ')),
                ('e_mail', models.CharField(blank=True, max_length=32, verbose_name='Email : ')),
            ],
        ),
        migrations.RemoveField(
            model_name='main_page_ru',
            name='about_company',
        ),
        migrations.RemoveField(
            model_name='main_page_ru',
            name='company_name',
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='about_main',
            field=models.TextField(blank=True, verbose_name='Подробно'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product1_img',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Имя Продукта 1'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product1_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Текст Продукции 1'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product2_img',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Имя Продукта 2'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product2_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Текст Продукции 2:'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product3_img',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Имя Продукта 3'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product3_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Текст Продукции 3'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product4_img',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Имя Продукта 4'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product4_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Текст Продукции 4'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product5_img',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Имя Продукта 5'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product5_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Текст Продукции 5'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product6_img',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Имя Продукта 6'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product6_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Текст Продукции 6'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product7_img',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Имя Продукта 7'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product7_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Текст Продукции 7'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product8_img',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Имя Продукта 8'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='dif_product8_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Текст Продукции 8'),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='main_title',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя '),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='property1_title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Имя Услуги1: '),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='property2_title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Имя Услуги2: '),
        ),
        migrations.AddField(
            model_name='main_page_ru',
            name='property3_title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Имя Услуги3: '),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide1',
            field=models.TextField(blank=True, verbose_name='Слайд1 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide2',
            field=models.TextField(blank=True, verbose_name='Слайд2 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide3',
            field=models.TextField(blank=True, verbose_name='Слайд3 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide4',
            field=models.TextField(blank=True, verbose_name='Слайд4 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide5',
            field=models.TextField(blank=True, verbose_name='Слайд5 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide6',
            field=models.TextField(blank=True, verbose_name='Слайд6 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide1',
            field=models.CharField(blank=True, max_length=32, verbose_name='Слайд1 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide2',
            field=models.CharField(blank=True, max_length=32, verbose_name='Слайд2 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide3',
            field=models.CharField(blank=True, max_length=32, verbose_name='Слайд3 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide4',
            field=models.CharField(blank=True, max_length=32, verbose_name='Слайд4 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide5',
            field=models.CharField(blank=True, max_length=32, verbose_name='Слайд5 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide6',
            field=models.CharField(blank=True, max_length=32, verbose_name='Слайд6 текст'),
        ),
        migrations.AlterField(
            model_name='product_ru',
            name='is_new',
            field=models.BooleanField(default=1, verbose_name='Новый'),
        ),
        migrations.AlterField(
            model_name='product_ru',
            name='product_description',
            field=models.TextField(blank=True, verbose_name='Подробно'),
        ),
    ]
