# Generated by Django 2.2.9 on 2020-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0004_auto_20200127_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_page',
            name='dif_product1',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Harydyň ady 1'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product2',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Harydyň ady 2'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product3',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Harydyň ady 3'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product4',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Harydyň ady 4'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product5',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Harydyň ady 5'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product6',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Harydyň ady 6'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product7',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Harydyň ady 7'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product8',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Harydyň ady 8'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide1',
            field=models.TextField(blank=True, verbose_name='Slayt1 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide2',
            field=models.TextField(blank=True, verbose_name='Slayt2 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide3',
            field=models.TextField(blank=True, verbose_name='Slayt3 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide4',
            field=models.TextField(blank=True, verbose_name='Slayt4 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide5',
            field=models.TextField(blank=True, verbose_name='Slayt5 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide6',
            field=models.TextField(blank=True, verbose_name='Slayt6 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide1',
            field=models.CharField(blank=True, max_length=32, verbose_name='Slayt1 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide2',
            field=models.CharField(blank=True, max_length=32, verbose_name='Slayt2 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide3',
            field=models.CharField(blank=True, max_length=32, verbose_name='Slayt3 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide4',
            field=models.CharField(blank=True, max_length=32, verbose_name='Slayt4 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide5',
            field=models.CharField(blank=True, max_length=32, verbose_name='Slayt5 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide6',
            field=models.CharField(blank=True, max_length=32, verbose_name='Slayt6 tekst'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, verbose_name='Haryt Barada Giňişleýin Maglumat'),
        ),
    ]
