# Generated by Django 2.2.9 on 2020-02-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0005_auto_20200203_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_page',
            old_name='dif_product1',
            new_name='dif_product1_img',
        ),
        migrations.RenameField(
            model_name='main_page',
            old_name='dif_product2',
            new_name='dif_product2_img',
        ),
        migrations.RenameField(
            model_name='main_page',
            old_name='dif_product3',
            new_name='dif_product3_img',
        ),
        migrations.RenameField(
            model_name='main_page',
            old_name='dif_product4',
            new_name='dif_product4_img',
        ),
        migrations.RenameField(
            model_name='main_page',
            old_name='dif_product5',
            new_name='dif_product5_img',
        ),
        migrations.RenameField(
            model_name='main_page',
            old_name='dif_product6',
            new_name='dif_product6_img',
        ),
        migrations.RenameField(
            model_name='main_page',
            old_name='dif_product7',
            new_name='dif_product7_img',
        ),
        migrations.RenameField(
            model_name='main_page',
            old_name='dif_product8',
            new_name='dif_product8_img',
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product1_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Harytlar Teksti 1:'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product2_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Harytlar Teksti 2:'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product3_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Harytlar Teksti 3:'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product4_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Harytlar Teksti 4:'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product5_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Harytlar Teksti 5:'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product6_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Harytlar Teksti 6:'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product7_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Harytlar Teksti 7:'),
        ),
        migrations.AddField(
            model_name='main_page',
            name='dif_product8_txt',
            field=models.CharField(blank=True, max_length=32, verbose_name='Harytlar Teksti 8:'),
        ),
    ]
