# Generated by Django 2.2.9 on 2020-02-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0007_auto_20200203_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_page',
            name='property1_title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Hyzmat Ady 1: '),
        ),
        migrations.AddField(
            model_name='main_page',
            name='property2_title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Hyzmat Ady 2: '),
        ),
        migrations.AddField(
            model_name='main_page',
            name='property3_title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Hyzmat Ady 3: '),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_property1',
            field=models.TextField(verbose_name='Hyzmat1 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_property2',
            field=models.TextField(verbose_name='Hyzmat2 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_property3',
            field=models.TextField(verbose_name='Hyzmat3 Giňişleýin'),
        ),
    ]
